services:
  - type: web
    name: book-social-network-backend
    env: java
    rootDir: book-network
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/book-network-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: book-social-network-db
          property: connectionString
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m

